ckan:
  build: .
  links:
      - db
      - solr
      - redis
  ports:
      - "80:5000"
  volumes:
      - ./datastore:/var/lib/ckan

db:
  ports:
      - "5432:5432"
  container_name: db
  build: postgresql/
  
solr:
  ports:
    - "8983:8983"
  container_name: solr
  image: ckan/solr:latest

web:
  image: nginx
  links:
    - ckan
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./ssl:/etc/nginx/ssl
  ports:
    - "443:443"
    
redis:
  container_name: redis
  image: redis:latest
